apiVersion: v1
kind: Pod
metadata:
  labels:
    app: http-server
  name: http-server-liveness
spec:
  containers:
    - name: http-server
      image: blux2/delayfailserver:1.1
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
